/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 주문 주소 생성 요청 DTO
 */
export interface AddressCreateReqDto {
  /** @minLength 1 */
  address: string;
  addressDetail?: string;
  deliveryMemo?: string;
  /**
   * @minLength 9
   * @maxLength 20
   */
  phoneNumber: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  receiverName: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  sido: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  sigungu: string;
  /**
   * @minLength 1
   * @pattern \d{5}
   */
  zipCode: string;
}
