/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AttributeKey = typeof AttributeKey[keyof typeof AttributeKey];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttributeKey = {
  SIZE_LABEL: 'SIZE_LABEL',
} as const;
