/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AttributeKey } from './attributeKey';

/**
 * Product 요소 수정 요청 DTO
 */
export interface AttributeUpdateReqDto {
  id?: number;
  attributeKey: AttributeKey;
  /**
   * @minLength 0
   * @maxLength 255
   */
  attributeValue: string;
}
