/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AttributeCreateReqDtoAttributeKey = typeof AttributeCreateReqDtoAttributeKey[keyof typeof AttributeCreateReqDtoAttributeKey];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttributeCreateReqDtoAttributeKey = {
  SIZE_LABEL: 'SIZE_LABEL',
} as const;
