/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AttributeCreateReqDtoAttributeKey } from './attributeCreateReqDtoAttributeKey';

/**
 * Product 요소 생성 요청 DTO
 */
export interface AttributeCreateReqDto {
  attributeKey: AttributeCreateReqDtoAttributeKey;
  /**
   * @minLength 0
   * @maxLength 255
   */
  attributeValue: string;
}
