/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AttributeUpdateReqDtoAttributeKey = typeof AttributeUpdateReqDtoAttributeKey[keyof typeof AttributeUpdateReqDtoAttributeKey];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttributeUpdateReqDtoAttributeKey = {
  SIZE_LABEL: 'SIZE_LABEL',
} as const;
