/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 장바구니 SKU 수정 요청 DTO
 */
export interface CartItemSkuUpdateReqDto {
  /**
   * @minimum 1
   * @maximum 999
   */
  quantity: number;
  skuId: number;
}
