/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CartItemResDtoProductStatus = typeof CartItemResDtoProductStatus[keyof typeof CartItemResDtoProductStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CartItemResDtoProductStatus = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
  DISCONTINUED: 'DISCONTINUED',
  ARCHIVED: 'ARCHIVED',
} as const;
