/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 장바구니 수정 요청 DTO
 */
export interface CartItemUpdateReqDto {
  quantity?: number;
}
