/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 장바구니 상품 추가 요청 DTO
 */
export interface CartItemCreateReqDto {
  quantity: number;
  skuId: number;
}
