/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CartItemResDto } from './cartItemResDto';

export interface CartResDto {
  cartId?: number;
  items?: CartItemResDto[];
  totalPrice?: number;
}
