/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 장바구니 주문 전 조회 요청 DTO
 */
export interface CartOrderPreviewReqDto {
  /** 배송지 ID (미등록 회원은 null) */
  addressId?: number;
  /**
   * @minItems 1
   * @maxItems 2147483647
   */
  cartItemIds: number[];
}
