/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 장바구니 주문 생성 요청 DTO
 */
export interface CartOrderCreateReqDto {
  addressId: number;
  /**
   * @minItems 1
   * @maxItems 2147483647
   */
  cartItemIds: number[];
  /**
   * @minLength 0
   * @maxLength 255
   */
  deliveryMemo?: string;
  pointUsedAmount: number;
}
