/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductStatus } from './productStatus';
import type { SkuStatus } from './skuStatus';

export interface CartItemResDto {
  cartItemId?: number;
  color?: string;
  itemTotalPrice?: number;
  material?: string;
  productId?: number;
  productName?: string;
  productStatus?: ProductStatus;
  quantity?: number;
  skuId?: number;
  skuStatus?: SkuStatus;
  unitPrice?: number;
}
