/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 카테고리 수정 요청 DTO
 */
export interface CategoryUpdateReqDto {
  /**
   * @minLength 0
   * @maxLength 255
   */
  name: string;
  parentId?: number;
  sortOrder?: number;
}
