/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CategoryTreeResDtoStatus } from './categoryTreeResDtoStatus';

export interface CategoryTreeResDto {
  id?: number;
  name?: string;
  parentId?: number;
  depth?: number;
  sortOrder?: number;
  status?: CategoryTreeResDtoStatus;
}
