/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CategoryStatus } from './categoryStatus';

export interface CategoryResDto {
  depth?: number;
  id?: number;
  name?: string;
  parentId?: number;
  sortOrder?: number;
  status?: CategoryStatus;
}
