/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CategoryTreeResDtoStatus = typeof CategoryTreeResDtoStatus[keyof typeof CategoryTreeResDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryTreeResDtoStatus = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
  ARCHIVED: 'ARCHIVED',
} as const;
