/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CategoryResDtoStatus } from './categoryResDtoStatus';

export interface CategoryResDto {
  id?: number;
  name?: string;
  parentId?: number;
  depth?: number;
  sortOrder?: number;
  status?: CategoryResDtoStatus;
}
