/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CategoryStatus = typeof CategoryStatus[keyof typeof CategoryStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CategoryStatus = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
  ARCHIVED: 'ARCHIVED',
} as const;
