/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 주문 취소 상품 요청 DTO
 */
export interface ClaimItemReqDto {
  orderItemId: number;
  quantity: number;
}
