/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ClaimItemReqDto } from './claimItemReqDto';
import type { ClaimOrderReqDtoReason } from './claimOrderReqDtoReason';

/**
 * 주문 취소 요청 DTO
 */
export interface ClaimOrderReqDto {
  /**
   * @minItems 1
   * @maxItems 2147483647
   */
  claimItems: ClaimItemReqDto[];
  reason: ClaimOrderReqDtoReason;
  reasonDetail: string;
}
