/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ClaimOrderReqDtoReason = typeof ClaimOrderReqDtoReason[keyof typeof ClaimOrderReqDtoReason];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClaimOrderReqDtoReason = {
  CHANGE_OF_MIND: 'CHANGE_OF_MIND',
  FOUND_CHEAPER: 'FOUND_CHEAPER',
  DELIVERY_DELAYED: 'DELIVERY_DELAYED',
  DEFECTIVE: 'DEFECTIVE',
  WRONG_DELIVERY: 'WRONG_DELIVERY',
  DIFFERENT_FROM_DESCRIPTION: 'DIFFERENT_FROM_DESCRIPTION',
  ETC: 'ETC',
} as const;
