/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 구성품 수정 요청 DTO
 */
export interface CompositionUpdateReqDto {
  id?: number;
  childSkuId: number;
  quantity: number;
  sortOrder: number;
}
