/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 구성품 생성 요청 DTO
 */
export interface CompositionCreateReqDto {
  childSkuId: number;
  quantity: number;
  sortOrder: number;
}
