/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 구성품 응답 DTO
 */
export interface CompositionResDto {
  childSkuId?: number;
  childProductName?: string;
  quantity?: number;
  sortOrder?: number;
}
