/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DeliveryType } from './deliveryType';

export interface DeliveryPolicyResDto {
  baseFee?: number;
  deliveryType?: DeliveryType;
  freeShippingThreshold?: number;
}
