/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type DeliveryStatus = typeof DeliveryStatus[keyof typeof DeliveryStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeliveryStatus = {
  READY: 'READY',
  ASSIGNED: 'ASSIGNED',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  RETURNED: 'RETURNED',
} as const;
