/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type DeliveryResDtoDeliveryType = typeof DeliveryResDtoDeliveryType[keyof typeof DeliveryResDtoDeliveryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeliveryResDtoDeliveryType = {
  PARCEL: 'PARCEL',
  INSTALLATION: 'INSTALLATION',
} as const;
