/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type DeliveryType = typeof DeliveryType[keyof typeof DeliveryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeliveryType = {
  PARCEL: 'PARCEL',
  INSTALLATION: 'INSTALLATION',
} as const;
