/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DeliveryType } from './deliveryType';
import type { DeliveryStatus } from './deliveryStatus';

/**
 * 배송 정보 DTO
 */
export interface DeliveryResDto {
  deliveryId?: number;
  orderId?: number;
  deliveryType?: DeliveryType;
  status?: DeliveryStatus;
  /** 대표 상품명 */
  repProductName?: string;
  /** 상품 종류 수 */
  itemCnt?: number;
}
