/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DeliveryType } from './deliveryType';
import type { OrderPreviewItemResDto } from './orderPreviewItemResDto';

export interface DeliveryGroupResDto {
  deliveryFee?: number;
  deliveryType?: DeliveryType;
  groupAmount?: number;
  items?: OrderPreviewItemResDto[];
}
