/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderSkuReqDto } from './orderSkuReqDto';

/**
 * 바로 주문 전 조회 요청 DTO
 */
export interface DirectOrderPreviewReqDto {
  /** 배송지 ID (미등록 회원은 null) */
  addressId?: number;
  /**
   * @minItems 1
   * @maxItems 2147483647
   */
  orderSkus: OrderSkuReqDto[];
}
