/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderSkuReqDto } from './orderSkuReqDto';

/**
 * 바로 주문 생성 요청 DTO
 */
export interface DirectOrderCreateReqDto {
  addressId: number;
  /**
   * @minLength 0
   * @maxLength 255
   */
  deliveryMemo?: string;
  /**
   * @minItems 1
   * @maxItems 2147483647
   */
  orderSkus: OrderSkuReqDto[];
  pointUsedAmount: number;
}
