/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetProducts1StatusesItem = typeof GetProducts1StatusesItem[keyof typeof GetProducts1StatusesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetProducts1StatusesItem = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
  DISCONTINUED: 'DISCONTINUED',
  ARCHIVED: 'ARCHIVED',
} as const;
