/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 나의 배송지 생성 요청 DTO
 */
export interface MAddressCreateReqDto {
  /** @minLength 1 */
  address: string;
  addressDetail?: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  addressName: string;
  defaultAddress: boolean;
  /**
   * @minLength 9
   * @maxLength 20
   */
  phoneNumber: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  receiverName: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  sido: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  sigungu: string;
  /**
   * @minLength 1
   * @pattern \d{5}
   */
  zipCode: string;
}
