/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface MemberAddressResDto {
  address?: string;
  addressDetail?: string;
  addressId?: number;
  addressName?: string;
  defaultAddress?: boolean;
  phoneNumber?: string;
  receiverName?: string;
  sido?: string;
  sigungu?: string;
  zipCode?: string;
}
