/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 주문 주소 응답 DTO
 */
export interface OrderAddressResDto {
  receiverName?: string;
  phoneNumber?: string;
  zipCode?: string;
  address?: string;
  addressDetail?: string;
  sido?: string;
  sigungu?: string;
  deliveryMemo?: string;
}
