/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderWithDeliveryResDtoStatus } from './orderWithDeliveryResDtoStatus';
import type { DeliveryResDto } from './deliveryResDto';

/**
 * 주문 정보 및 배송 상태 DTO
 */
export interface OrderWithDeliveryResDto {
  orderId?: number;
  orderNumber?: string;
  status?: OrderWithDeliveryResDtoStatus;
  orderDate?: string;
  finalAmount?: number;
  deliveries?: DeliveryResDto[];
}
