/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AddressCreateReqDto } from './addressCreateReqDto';

/**
 * 주문 생성 요청 DTO
 */
export interface OrderCreateReqDto {
  /**
   * @minItems 1
   * @maxItems 2147483647
   */
  cartItems: number[];
  orderAddress: AddressCreateReqDto;
  pointUsedAmount: number;
}
