/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DeliveryGroupResDto } from './deliveryGroupResDto';

/**
 * 주문 전 조회 응답 DTO
 */
export interface OrderPreviewResDto {
  /** 배송 타입별 배송비 합계 */
  deliveryFee?: number;
  deliveryGroups?: DeliveryGroupResDto[];
  /** 쿠폰·프로모션 할인 */
  discountAmount?: number;
  finalAmount?: number;
  /** Σ(판매가 × 수량) */
  totalAmount?: number;
  /** Σ(정가 × 수량), 화면 표시용 */
  totalOriginalAmount?: number;
}
