/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DeliveryResDto } from './deliveryResDto';
import type { OrderStatus } from './orderStatus';

/**
 * 주문 정보 및 배송 상태 DTO
 */
export interface OrderWithDeliveryResDto {
  deliveries?: DeliveryResDto[];
  finalAmount?: number;
  orderDate?: string;
  orderId?: number;
  orderNumber?: string;
  status?: OrderStatus;
}
