/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderStatus } from './orderStatus';
import type { OrderAddressResDto } from './orderAddressResDto';
import type { OrderItemResDto } from './orderItemResDto';

/**
 * 주문 응답 DTO
 */
export interface OrderWithAllResDto {
  orderId?: number;
  orderNumber?: string;
  status?: OrderStatus;
  orderDate?: string;
  totalAmount?: number;
  discountAmount?: number;
  pointUsedAmount?: number;
  deliveryFee?: number;
  finalAmount?: number;
  address?: OrderAddressResDto;
  items?: OrderItemResDto[];
}
