/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 바로 주문 SKU 요청 DTO
 */
export interface OrderSkuReqDto {
  /**
   * @minimum 1
   * @maximum 999
   */
  quantity: number;
  skuId: number;
}
