/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type OrderItemResDtoStatus = typeof OrderItemResDtoStatus[keyof typeof OrderItemResDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderItemResDtoStatus = {
  ORDERED: 'ORDERED',
  CANCEL_REQUESTED: 'CANCEL_REQUESTED',
  CANCELLED: 'CANCELLED',
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  RETURNED: 'RETURNED',
} as const;
