/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderItemStatus } from './orderItemStatus';

/**
 * 주문 제품 응답 DTO
 */
export interface OrderItemResDto {
  discountAmount?: number;
  id?: number;
  itemTotalAmount?: number;
  productName?: string;
  quantity?: number;
  skuId?: number;
  skuIdentifier?: string;
  status?: OrderItemStatus;
  unitPrice?: number;
}
