/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type OrderWithDeliveryResDtoStatus = typeof OrderWithDeliveryResDtoStatus[keyof typeof OrderWithDeliveryResDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderWithDeliveryResDtoStatus = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  PREPARING: 'PREPARING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  RETURNED: 'RETURNED',
} as const;
