/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DeliveryType } from './deliveryType';

export interface OrderPreviewItemResDto {
  color?: string;
  deliveryType?: DeliveryType;
  discountRate?: number;
  itemTotalAmount?: number;
  mainImageUrl?: string;
  material?: string;
  originalPrice?: number;
  productId?: number;
  productName?: string;
  quantity?: number;
  salePrice?: number;
  skuId?: number;
}
