/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductResDto } from './productResDto';
import type { SortObject } from './sortObject';
import type { PageableObject } from './pageableObject';

export interface PageProductResDto {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: ProductResDto[];
  number?: number;
  sort?: SortObject;
  first?: boolean;
  last?: boolean;
  numberOfElements?: number;
  pageable?: PageableObject;
  empty?: boolean;
}
