/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderWithDeliveryResDto } from './orderWithDeliveryResDto';
import type { PageableObject } from './pageableObject';
import type { SortObject } from './sortObject';

export interface PageOrderWithDeliveryResDto {
  content?: OrderWithDeliveryResDto[];
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: PageableObject;
  size?: number;
  sort?: SortObject;
  totalElements?: number;
  totalPages?: number;
}
