/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 결제 승인 요청 DTO
 */
export interface PaymentApproveReqDto {
  /**
   * @minLength 0
   * @maxLength 200
   */
  paymentKey: string;
}
