/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PaymentPrepareReqDtoPgProvider = typeof PaymentPrepareReqDtoPgProvider[keyof typeof PaymentPrepareReqDtoPgProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentPrepareReqDtoPgProvider = {
  TOSS: 'TOSS',
} as const;
