/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PaymentPrepareResDtoPgProvider } from './paymentPrepareResDtoPgProvider';
import type { PaymentPrepareResDtoPaymentMethod } from './paymentPrepareResDtoPaymentMethod';

/**
 * 결제 준비 응답 DTO
 */
export interface PaymentPrepareResDto {
  orderId?: number;
  paymentId?: number;
  paymentNumber?: string;
  pgProvider?: PaymentPrepareResDtoPgProvider;
  paymentMethod?: PaymentPrepareResDtoPaymentMethod;
  totalAmount?: number;
}
