/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PaymentPrepareReqDtoPgProvider } from './paymentPrepareReqDtoPgProvider';
import type { PaymentPrepareReqDtoPaymentMethod } from './paymentPrepareReqDtoPaymentMethod';

/**
 * 결제 준비 요청 DTO
 */
export interface PaymentPrepareReqDto {
  orderId: number;
  pgProvider: PaymentPrepareReqDtoPgProvider;
  paymentMethod: PaymentPrepareReqDtoPaymentMethod;
}
