/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PaymentMethod } from './paymentMethod';
import type { PgProvider } from './pgProvider';

/**
 * 결제 준비 요청 DTO
 */
export interface PaymentPrepareReqDto {
  orderId: number;
  paymentMethod: PaymentMethod;
  pgProvider: PgProvider;
}
