/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PaymentPrepareResDtoPgProvider = typeof PaymentPrepareResDtoPgProvider[keyof typeof PaymentPrepareResDtoPgProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentPrepareResDtoPgProvider = {
  TOSS: 'TOSS',
} as const;
