/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PaymentPrepareReqDtoPaymentMethod = typeof PaymentPrepareReqDtoPaymentMethod[keyof typeof PaymentPrepareReqDtoPaymentMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentPrepareReqDtoPaymentMethod = {
  CARD: 'CARD',
  TRANSFER: 'TRANSFER',
  EASY_PAY: 'EASY_PAY',
  PHONE: 'PHONE',
} as const;
