/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PaymentMethod } from './paymentMethod';
import type { PgProvider } from './pgProvider';

/**
 * 결제 준비 응답 DTO
 */
export interface PaymentPrepareResDto {
  orderId?: number;
  paymentId?: number;
  paymentMethod?: PaymentMethod;
  paymentNumber?: string;
  pgProvider?: PgProvider;
  totalAmount?: number;
}
