/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PgProvider = typeof PgProvider[keyof typeof PgProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PgProvider = {
  TOSS: 'TOSS',
} as const;
