/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AttributeUpdateReqDto } from './attributeUpdateReqDto';
import type { CompositionUpdateReqDto } from './compositionUpdateReqDto';
import type { DeliveryType } from './deliveryType';
import type { SkuUpdateReqDto } from './skuUpdateReqDto';

/**
 * 상품 수정 요청 DTO
 */
export interface ProductUpdateReqDto {
  attributes?: AttributeUpdateReqDto[];
  categoryId: number;
  compositions?: CompositionUpdateReqDto[];
  deliveryType: DeliveryType;
  depth: number;
  description?: string;
  height: number;
  /**
   * @minLength 0
   * @maxLength 255
   */
  name: string;
  /**
   * @minItems 1
   * @maxItems 2147483647
   */
  skus: SkuUpdateReqDto[];
  weight: number;
  width: number;
}
