/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ProductWithSkuResDtoDeliveryType = typeof ProductWithSkuResDtoDeliveryType[keyof typeof ProductWithSkuResDtoDeliveryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductWithSkuResDtoDeliveryType = {
  PARCEL: 'PARCEL',
  INSTALLATION: 'INSTALLATION',
} as const;
