/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ProductAttributeResDtoAttributeKey = typeof ProductAttributeResDtoAttributeKey[keyof typeof ProductAttributeResDtoAttributeKey];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductAttributeResDtoAttributeKey = {
  SIZE_LABEL: 'SIZE_LABEL',
} as const;
