/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ProductWithAllResDtoDeliveryType = typeof ProductWithAllResDtoDeliveryType[keyof typeof ProductWithAllResDtoDeliveryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductWithAllResDtoDeliveryType = {
  PARCEL: 'PARCEL',
  INSTALLATION: 'INSTALLATION',
} as const;
