/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ProductResDtoProductType = typeof ProductResDtoProductType[keyof typeof ProductResDtoProductType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductResDtoProductType = {
  COMPLETE: 'COMPLETE',
  COMPONENT: 'COMPONENT',
} as const;
