/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AttributeKey } from './attributeKey';

export interface ProductAttributeResDto {
  attributeKey?: AttributeKey;
  attributeValue?: string;
  id?: number;
}
