/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ProductUpdateReqDtoDeliveryType = typeof ProductUpdateReqDtoDeliveryType[keyof typeof ProductUpdateReqDtoDeliveryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductUpdateReqDtoDeliveryType = {
  PARCEL: 'PARCEL',
  INSTALLATION: 'INSTALLATION',
} as const;
