/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ProductWithAllResDtoProductType = typeof ProductWithAllResDtoProductType[keyof typeof ProductWithAllResDtoProductType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductWithAllResDtoProductType = {
  COMPLETE: 'COMPLETE',
  COMPONENT: 'COMPONENT',
} as const;
