/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ProductCreateReqDtoDeliveryType = typeof ProductCreateReqDtoDeliveryType[keyof typeof ProductCreateReqDtoDeliveryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductCreateReqDtoDeliveryType = {
  PARCEL: 'PARCEL',
  INSTALLATION: 'INSTALLATION',
} as const;
