/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductCreateReqDtoProductType } from './productCreateReqDtoProductType';
import type { ProductCreateReqDtoDeliveryType } from './productCreateReqDtoDeliveryType';
import type { SkuCreateReqDto } from './skuCreateReqDto';
import type { AttributeCreateReqDto } from './attributeCreateReqDto';
import type { CompositionCreateReqDto } from './compositionCreateReqDto';

/**
 * 상품 생성 요청 DTO
 */
export interface ProductCreateReqDto {
  categoryId: number;
  /**
   * @minLength 0
   * @maxLength 255
   */
  name: string;
  description?: string;
  productType: ProductCreateReqDtoProductType;
  deliveryType: ProductCreateReqDtoDeliveryType;
  weight: number;
  width: number;
  height: number;
  depth: number;
  /**
   * @minItems 1
   * @maxItems 2147483647
   */
  skus: SkuCreateReqDto[];
  attributes?: AttributeCreateReqDto[];
  compositions?: CompositionCreateReqDto[];
}
