/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductResDtoStatus } from './productResDtoStatus';
import type { ProductResDtoProductType } from './productResDtoProductType';

export interface ProductResDto {
  id?: number;
  name?: string;
  basePrice?: number;
  status?: ProductResDtoStatus;
  productType?: ProductResDtoProductType;
  isSoldOut?: boolean;
}
