/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductAttributeResDto } from './productAttributeResDto';
import type { CompositionResDto } from './compositionResDto';
import type { DeliveryType } from './deliveryType';
import type { ProductType } from './productType';
import type { SkuWithStockResDto } from './skuWithStockResDto';
import type { ProductStatus } from './productStatus';

/**
 * 제품 응답 DTO (관리자용)
 */
export interface ProductWithAllResDto {
  attributes?: ProductAttributeResDto[];
  basePrice?: number;
  compositions?: CompositionResDto[];
  deliveryType?: DeliveryType;
  depth?: number;
  description?: string;
  height?: number;
  id?: number;
  isSoldOut?: boolean;
  name?: string;
  productType?: ProductType;
  skus?: SkuWithStockResDto[];
  status?: ProductStatus;
  weight?: number;
  width?: number;
}
