/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ProductWithSkuResDtoProductType = typeof ProductWithSkuResDtoProductType[keyof typeof ProductWithSkuResDtoProductType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductWithSkuResDtoProductType = {
  COMPLETE: 'COMPLETE',
  COMPONENT: 'COMPONENT',
} as const;
