/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ProductCreateReqDtoProductType = typeof ProductCreateReqDtoProductType[keyof typeof ProductCreateReqDtoProductType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductCreateReqDtoProductType = {
  COMPLETE: 'COMPLETE',
  COMPONENT: 'COMPONENT',
} as const;
