/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductWithSkuResDtoProductType } from './productWithSkuResDtoProductType';
import type { ProductWithSkuResDtoDeliveryType } from './productWithSkuResDtoDeliveryType';
import type { ProductWithSkuResDtoStatus } from './productWithSkuResDtoStatus';
import type { SkuResDto } from './skuResDto';

/**
 * 제품 응답 DTO
 */
export interface ProductWithSkuResDto {
  id?: number;
  name?: string;
  description?: string;
  productType?: ProductWithSkuResDtoProductType;
  deliveryType?: ProductWithSkuResDtoDeliveryType;
  status?: ProductWithSkuResDtoStatus;
  basePrice?: number;
  weight?: number;
  width?: number;
  height?: number;
  depth?: number;
  isSoldOut?: boolean;
  skus?: SkuResDto[];
}
