/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DeliveryType } from './deliveryType';
import type { ProductType } from './productType';
import type { SkuResDto } from './skuResDto';
import type { ProductStatus } from './productStatus';

/**
 * 제품 응답 DTO
 */
export interface ProductWithSkuResDto {
  basePrice?: number;
  deliveryType?: DeliveryType;
  depth?: number;
  description?: string;
  height?: number;
  id?: number;
  isSoldOut?: boolean;
  name?: string;
  productType?: ProductType;
  skus?: SkuResDto[];
  status?: ProductStatus;
  weight?: number;
  width?: number;
}
