/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ProductType = typeof ProductType[keyof typeof ProductType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductType = {
  COMPLETE: 'COMPLETE',
  COMPONENT: 'COMPONENT',
} as const;
