/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductWithAllResDtoProductType } from './productWithAllResDtoProductType';
import type { ProductWithAllResDtoDeliveryType } from './productWithAllResDtoDeliveryType';
import type { ProductWithAllResDtoStatus } from './productWithAllResDtoStatus';
import type { SkuWithStockResDto } from './skuWithStockResDto';
import type { ProductAttributeResDto } from './productAttributeResDto';
import type { CompositionResDto } from './compositionResDto';

/**
 * 제품 응답 DTO (관리자용)
 */
export interface ProductWithAllResDto {
  id?: number;
  name?: string;
  description?: string;
  productType?: ProductWithAllResDtoProductType;
  deliveryType?: ProductWithAllResDtoDeliveryType;
  status?: ProductWithAllResDtoStatus;
  basePrice?: number;
  weight?: number;
  width?: number;
  height?: number;
  depth?: number;
  isSoldOut?: boolean;
  skus?: SkuWithStockResDto[];
  attributes?: ProductAttributeResDto[];
  compositions?: CompositionResDto[];
}
