/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageOrderWithDeliveryResDto } from './pageOrderWithDeliveryResDto';

export interface RsDataPageOrderWithDeliveryResDto {
  code?: string;
  message?: string;
  data?: PageOrderWithDeliveryResDto;
}
