/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PageProductResDto } from './pageProductResDto';

export interface RsDataPageProductResDto {
  code?: string;
  message?: string;
  data?: PageProductResDto;
}
