/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SkuResDto } from './skuResDto';

export interface RsDataListSkuResDto {
  code?: string;
  data?: SkuResDto[];
  message?: string;
}
