/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductFilterResDto } from './productFilterResDto';

export interface RsDataProductFilterResDto {
  code?: string;
  data?: ProductFilterResDto;
  message?: string;
}
