/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PaymentPrepareResDto } from './paymentPrepareResDto';

export interface RsDataPaymentPrepareResDto {
  code?: string;
  data?: PaymentPrepareResDto;
  message?: string;
}
