/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductWithSkuResDto } from './productWithSkuResDto';

export interface RsDataProductWithSkuResDto {
  code?: string;
  message?: string;
  data?: ProductWithSkuResDto;
}
