/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductAttributeResDto } from './productAttributeResDto';

export interface RsDataListProductAttributeResDto {
  code?: string;
  data?: ProductAttributeResDto[];
  message?: string;
}
