/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { DeliveryPolicyResDto } from './deliveryPolicyResDto';

export interface RsDataListDeliveryPolicyResDto {
  code?: string;
  data?: DeliveryPolicyResDto[];
  message?: string;
}
