/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CategoryTreeResDto } from './categoryTreeResDto';

export interface RsDataListCategoryTreeResDto {
  code?: string;
  message?: string;
  data?: CategoryTreeResDto[];
}
