/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CompositionResDto } from './compositionResDto';

export interface RsDataListCompositionResDto {
  code?: string;
  data?: CompositionResDto[];
  message?: string;
}
