/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MemberAddressResDto } from './memberAddressResDto';

export interface RsDataMemberAddressResDto {
  code?: string;
  data?: MemberAddressResDto;
  message?: string;
}
