/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OrderPreviewResDto } from './orderPreviewResDto';

export interface RsDataOrderPreviewResDto {
  code?: string;
  data?: OrderPreviewResDto;
  message?: string;
}
