/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductWithAllResDto } from './productWithAllResDto';

export interface RsDataProductWithAllResDto {
  code?: string;
  message?: string;
  data?: ProductWithAllResDto;
}
