/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AuthResDto } from './authResDto';

export interface RsDataAuthResDto {
  code?: string;
  message?: string;
  data?: AuthResDto;
}
