/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CategoryResDto } from './categoryResDto';

export interface RsDataCategoryResDto {
  code?: string;
  message?: string;
  data?: CategoryResDto;
}
