/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 로그인 요청 DTO
 */
export interface SignInReqDto {
  /**
   * @minLength 6
   * @maxLength 254
   */
  email: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string;
}
