/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * 회원가입 요청 DTO
 */
export interface SignUpReqDto {
  /**
   * @minLength 6
   * @maxLength 254
   */
  email: string;
  /**
   * @minLength 2
   * @maxLength 50
   */
  name: string;
  /**
   * @minLength 2
   * @maxLength 60
   */
  nickname: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string;
}
