/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * SKU 생성 요청 DTO
 */
export interface SkuCreateReqDto {
  price: number;
  stockQuantity: number;
  colorId?: number;
  materialId?: number;
}
