/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * SKU 생성 요청 DTO
 */
export interface SkuCreateReqDto {
  price: number;
  stockQuantity: number;
  /**
   * @minLength 0
   * @maxLength 50
   */
  color?: string;
  /**
   * @minLength 0
   * @maxLength 50
   */
  material?: string;
}
