/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SkuResDtoStatus } from './skuResDtoStatus';

/**
 * SKU 응답 DTO
 */
export interface SkuResDto {
  id?: number;
  price?: number;
  status?: SkuResDtoStatus;
  color?: string;
  material?: string;
}
