/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SkuStatus } from './skuStatus';

/**
 * SKU 응답 DTO
 */
export interface SkuResDto {
  color?: string;
  discountRate?: number;
  id?: number;
  isSoldOut?: boolean;
  material?: string;
  originalPrice?: number;
  salePrice?: number;
  status?: SkuStatus;
}
