/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SkuStatus = typeof SkuStatus[keyof typeof SkuStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SkuStatus = {
  ACTIVE: 'ACTIVE',
  SOLDOUT: 'SOLDOUT',
  DISCONTINUED: 'DISCONTINUED',
  ARCHIVED: 'ARCHIVED',
} as const;
