/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * SKU 수정 요청 DTO
 */
export interface SkuUpdateReqDto {
  colorId?: number;
  id?: number;
  materialId?: number;
  price: number;
  stockQuantity: number;
}
