/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SkuStatus } from './skuStatus';

/**
 * SKU 응답 DTO (관리자용)
 */
export interface SkuWithStockResDto {
  id?: number;
  price?: number;
  stockQuantity?: number;
  reservedQuantity?: number;
  status?: SkuStatus;
  color?: string;
  material?: string;
}
